#!/usr/bin/python3
from sys import argv

with open(argv[1]) as a:
    for line in a:
        number = int(line)
        print("{:d}=".format(number), end="")
        if number % 2 == 0:
            print("{}*2".format(number//2))
            continue
        for b in range(3, number, 2):
            if number % b == 0:
                factor = number//b
                for c in range(3, factor, 2):
                    if factor % c == 0 or b % c == 0:
                        break
                print("{}*{}".format(factor, b))
                break
